defmodule OfficeGraph.Architecture.AshApiLedgerConformanceTest do
  use OfficeGraph.TestSupport.AshConformanceSupport

  test "stabilization inventory documents current API domain and frontend debt" do
    assert File.exists?(@stabilization_inventory),
           "Expected stabilization inventory at #{@stabilization_inventory}"

    inventory = File.read!(@stabilization_inventory)

    for required_text <- [
          "## Active OpenSpec Scope",
          "## Manual API Surface Inventory",
          "## Domain And Database Exception Inventory",
          "## Broad Authorization Bypass Inventory",
          "## Frontend Architecture Gap Inventory",
          "OfficeGraphWeb.GraphQL.Schema",
          "OfficeGraph.ApiSupport",
          "assets/package.json"
        ] do
      assert inventory =~ required_text,
             "#{@stabilization_inventory} must document #{inspect(required_text)}"
    end
  end

  test "manual GraphQL and JSON API surfaces are covered by migration ledger entries" do
    unledgered =
      manual_api_surfaces()
      |> Enum.reject(&api_migration_ledger_approves_surface?(api_migration_ledger_entries(), &1))

    assert unledgered == [],
           """
           Found manual API surfaces without migration ledger coverage.
           Each surface must record owner, reason, replacement target, safety/parity tests, and retirement condition in #{@api_migration_ledger}.

           #{format_api_surfaces(unledgered)}
           """
  end

  test "manual API migration ledger entries still point to current surfaces" do
    current_surface_ids =
      manual_api_surfaces()
      |> MapSet.new(& &1.id)

    stale =
      for entry <- api_migration_ledger_entries(),
          not MapSet.member?(current_surface_ids, entry.id) do
        entry.id
      end

    assert stale == [],
           "#{@api_migration_ledger} contains surface ids with no matching current manual API surface:\n#{format_errors(stale)}"
  end

  test "manual API migration ledger records required approval metadata" do
    errors =
      @api_migration_ledger
      |> File.read!()
      |> api_migration_ledger_metadata_errors()

    assert errors == [],
           """
           #{@api_migration_ledger} entries must document owner, capability, exception class, reason, replacement target, safety/parity tests, and retirement condition:
           #{format_errors(errors)}
           """
  end

  test "selected resource reads are generated through AshGraphql and AshJsonApi" do
    schema = File.read!("lib/office_graph_web/graphql/schema.ex")
    json_router = File.read!("lib/office_graph_web/json_api/router.ex")
    phoenix_router = File.read!("lib/office_graph_web/router.ex")

    assert schema =~ "use AshGraphql"
    assert schema =~ "OfficeGraph.WorkGraph.Domain"
    assert schema =~ "OfficeGraph.WorkPackets.Domain"
    assert schema =~ "OfficeGraph.Runs.Domain"

    assert json_router =~ "use AshJsonApi.Router"
    assert json_router =~ "OfficeGraph.WorkGraph.Domain"
    assert json_router =~ "OfficeGraph.WorkPackets.Domain"
    assert json_router =~ "OfficeGraph.Runs.Domain"
    assert json_router =~ "prefix: \"/api/v1\""
    assert phoenix_router =~ "forward \"/api/v1\", OfficeGraphWeb.JsonApi.Router"

    for {domain_path, resource, graphql_read, json_route} <- [
          {"lib/office_graph/work_graph/domain.ex", "OfficeGraph.WorkGraph.Signal",
           ":list_signals", "\"/signals\""},
          {"lib/office_graph/work_packets/domain.ex", "OfficeGraph.WorkPackets.WorkPacket",
           ":list_work_packets", "\"/work-packets\""},
          {"lib/office_graph/runs/domain.ex", "OfficeGraph.Runs.Run", ":list_work_runs",
           "\"/work-runs\""}
        ] do
      domain = File.read!(domain_path)

      assert domain =~ "extensions: [AshGraphql.Domain, AshJsonApi.Domain]"
      assert domain =~ "list #{resource}, #{graphql_read}, :read"
      assert domain =~ "base_route #{json_route}, #{resource}"
      assert domain =~ "index :read"
    end
  end

  test "selected generated resource reads do not have manual API duplicates" do
    manual_graphql_sources =
      Path.wildcard("lib/office_graph_web/graphql/**/*.ex")
      |> Enum.reject(&(&1 == "lib/office_graph_web/graphql/schema.ex"))
      |> Enum.map(fn path -> {path, File.read!(path)} end)

    for {field, source_name} <- [
          {:list_signals, "listSignals"},
          {:list_work_packets, "listWorkPackets"},
          {:list_work_runs, "listWorkRuns"}
        ] do
      duplicates =
        for {path, source} <- manual_graphql_sources,
            source =~ "field #{inspect(field)}" do
          path
        end

      assert duplicates == [],
             "#{source_name} must stay generated by AshGraphql, not hand-written in #{inspect(duplicates)}"
    end

    manual_json_router_source = File.read!("lib/office_graph_web/router.ex")

    for route <- ["/signals", "/work-packets", "/work-runs"] do
      refute manual_json_router_source =~ route,
             "#{route} must stay generated by AshJsonApi under /api/v1, not hand-written in Phoenix routes"
    end
  end

  test "generated Ash API declarations stay declarative" do
    forbidden_patterns = [
      "OfficeGraphWeb.",
      "Absinthe.",
      "Plug.",
      "Phoenix.Controller",
      "RequestSession",
      "Serializer",
      "Controller",
      "put_status",
      "send_resp",
      "json(conn",
      "render(conn"
    ]

    offenders =
      ash_api_declaration_files()
      |> Enum.flat_map(fn path ->
        source = File.read!(path)

        for pattern <- forbidden_patterns,
            source =~ pattern do
          "#{path} contains #{inspect(pattern)}"
        end
      end)

    assert offenders == [],
           """
           Generated AshGraphql/AshJsonApi declarations must stay declarative.
           Keep request/session loading, response mapping, serializers, controllers, and custom Absinthe resolver behavior in OfficeGraphWeb transport modules.

           #{format_errors(offenders)}
           """
  end

  test "ApiSupport only bootstraps the local API owner" do
    source = File.read!("lib/office_graph/api_support.ex")

    direct_ecto_operations =
      scan_file_for_direct_ecto_operations("lib/office_graph/api_support.ex")

    assert source =~ "def bootstrap_local_api_owner"
    assert source =~ "Foundation.bootstrap_local_owner"

    refute source =~ "def submit_manual_intake"
    refute source =~ "def apply_proposed_changes"
    refute source =~ "def complete_verification"
    refute source =~ "def read_operator_"
    refute source =~ "def with_request_session_context"
    refute source =~ "Projections"
    refute source =~ "Integrations"

    refute Enum.any?(direct_ecto_operations, &(&1.operation == "Repo.transaction")),
           "ApiSupport must stay limited to API owner bootstrap"
  end

  test "manual GraphQL schema code is split under the GraphQL transport namespace" do
    assert File.exists?("lib/office_graph_web/graphql/schema.ex"),
           "Expected root GraphQL schema at lib/office_graph_web/graphql/schema.ex"

    refute File.exists?("lib/office_graph_web/schema.ex"),
           "Move the legacy monolithic schema into OfficeGraphWeb.GraphQL.* modules"

    graphql_modules =
      "lib/office_graph_web/graphql/**/*.ex"
      |> Path.wildcard()
      |> Enum.flat_map(&modules_in_file/1)

    for {path, module} <- graphql_modules do
      assert String.starts_with?(module, "OfficeGraphWeb.GraphQL."),
             "#{path} defines #{module}; GraphQL code must use OfficeGraphWeb.GraphQL.*"
    end

    for required_path <- [
          "lib/office_graph_web/graphql/schema.ex",
          "lib/office_graph_web/graphql/common/errors.ex",
          "lib/office_graph_web/graphql/common/queries.ex",
          "lib/office_graph_web/graphql/operator_workflow/types.ex",
          "lib/office_graph_web/graphql/operator_workflow/queries.ex",
          "lib/office_graph_web/graphql/operator_commands/types.ex",
          "lib/office_graph_web/graphql/operator_commands/mutations.ex"
        ] do
      assert File.exists?(required_path),
             "Expected GraphQL transport module file #{required_path}"
    end
  end

  test "operator command resolvers remain transport-only" do
    resolver_paths =
      "lib/office_graph_web/graphql/operator_commands/resolvers/*.ex"
      |> Path.wildcard()
      |> Enum.sort()

    assert length(resolver_paths) == 4

    for path <- resolver_paths do
      source = File.read!(path)
      resolver_body = source |> String.split("\n") |> tl() |> Enum.join("\n")

      refute source =~ "Repo.", "#{path} must not perform direct repository operations"
      refute source =~ "Ash.Changeset", "#{path} must not build Ash changesets"
      refute resolver_body =~ "Resolvers.", "#{path} must not call another resolver"

      refute source =~ "defp validate_",
             "#{path} must leave command validation inside the owning domain"

      assert source =~ "Input.parse", "#{path} must parse transport input"

      assert source =~ "RequestSession.resolve_resolution",
             "#{path} must resolve request sessions"

      assert source =~ "Operations.start_command", "#{path} must start server-owned commands"
    end
  end

  test "old compatibility GraphQL modules stay retired" do
    for retired_path <- [
          "lib/office_graph_web/graphql/compatibility/types.ex",
          "lib/office_graph_web/graphql/compatibility/mutations.ex"
        ] do
      refute File.exists?(retired_path), "Retired compatibility GraphQL file still exists"
    end

    schema_source = File.read!("lib/office_graph_web/graphql/schema.ex")
    old_module_name = "GraphQL." <> "Compatibility"

    refute schema_source =~ old_module_name
    refute schema_source =~ "compatibility_mutations"
  end

  test "manual JSON API code is split under the JSON API transport namespace" do
    old_json_api_paths =
      [
        "lib/office_graph_web/controllers/walking_skeleton_controller.ex",
        "lib/office_graph_web/controllers/operator_workflow_controller.ex",
        "lib/office_graph_web/controllers/packet_run_verification_controller.ex",
        "lib/office_graph_web/walking_skeleton_serializer.ex",
        "lib/office_graph_web/operator_workflow_serializer.ex",
        "lib/office_graph_web/packet_run_verification_serializer.ex"
      ]
      |> Enum.filter(&File.exists?/1)

    assert old_json_api_paths == [],
           "Move manual JSON API controllers and serializers under lib/office_graph_web/json_api:\n#{format_errors(old_json_api_paths)}"

    json_api_modules =
      "lib/office_graph_web/json_api/**/*.ex"
      |> Path.wildcard()
      |> Enum.flat_map(&modules_in_file/1)

    for {path, module} <- json_api_modules do
      assert String.starts_with?(module, "OfficeGraphWeb.JsonApi."),
             "#{path} defines #{module}; JSON API code must use OfficeGraphWeb.JsonApi.*"
    end

    for required_path <- [
          "lib/office_graph_web/json_api/common/errors.ex"
        ] do
      assert File.exists?(required_path),
             "Expected JSON API transport module file #{required_path}"
    end
  end

  test "old compatibility JSON routes stay retired" do
    for retired_path <- [
          "lib/office_graph_web/json_api/compatibility/controller.ex",
          "lib/office_graph_web/json_api/compatibility/serializer.ex"
        ] do
      refute File.exists?(retired_path), "Retired compatibility JSON file still exists"
    end

    router_source = File.read!("lib/office_graph_web/router.ex")
    old_module_name = "JsonApi." <> "Compatibility"

    for route <- [
          "/manual" <> "-intake",
          "/proposed" <> "-changes/apply",
          "/verification" <> "/complete"
        ] do
      refute router_source =~ route
    end

    refute router_source =~ old_module_name
  end

  test "old operator workflow JSON routes stay retired" do
    old_route_prefix = "/api/" <> "operator-workflow"
    old_module_name = "JsonApi." <> "OperatorWorkflow"

    for retired_path <- [
          "lib/office_graph_web/json_api/operator_workflow/controller.ex",
          "lib/office_graph_web/json_api/operator_workflow/serializer.ex"
        ] do
      refute File.exists?(retired_path), "Retired operator workflow JSON file still exists"
    end

    router_source = File.read!("lib/office_graph_web/router.ex")
    refute router_source =~ String.replace_prefix(old_route_prefix, "/api", "")
    refute router_source =~ old_module_name

    frontend_offenders =
      ["assets/app/**/*.ts*", "assets/src/operator/**/*.ts*"]
      |> Enum.flat_map(&Path.wildcard/1)
      |> Enum.reject(&(String.ends_with?(&1, ".test.ts") or String.ends_with?(&1, ".test.tsx")))
      |> Enum.filter(&(File.read!(&1) =~ old_route_prefix))

    assert frontend_offenders == [],
           "Production frontend code must not call old operator JSON routes:\n#{format_errors(frontend_offenders)}"
  end

  test "old packet-run JSON command stays retired" do
    for retired_path <- [
          "lib/office_graph_web/json_api/packet_run_verification/controller.ex",
          "lib/office_graph_web/json_api/packet_run_verification/serializer.ex"
        ] do
      refute File.exists?(retired_path), "Retired packet-run JSON file still exists"
    end

    router_source = File.read!("lib/office_graph_web/router.ex")
    old_route = "/packet" <> "-run-verification/execute"
    old_module_name = "JsonApi." <> Enum.join(["Packet", "Run", "Verification"])

    refute router_source =~ old_route
    refute router_source =~ old_module_name
  end

  test "GraphQL and JSON API helpers stay transport-specific" do
    generic_api_modules =
      "lib/office_graph_web/api/**/*.ex"
      |> Path.wildcard()
      |> Enum.concat(Path.wildcard("lib/office_graph_web/api.ex"))
      |> Enum.filter(&File.exists?/1)

    assert generic_api_modules == [],
           "Do not create a generic OfficeGraphWeb.Api dumping ground:\n#{format_errors(generic_api_modules)}"

    graphql_errors = "lib/office_graph_web/graphql/common/errors.ex"
    json_errors = "lib/office_graph_web/json_api/common/errors.ex"

    assert File.exists?(graphql_errors), "Expected #{graphql_errors}"
    assert File.exists?(json_errors), "Expected #{json_errors}"

    refute File.read!(graphql_errors) =~ "put_status",
           "GraphQL error mapping must not know about Plug/Phoenix response envelopes"

    refute File.read!(json_errors) =~ "extensions:",
           "JSON API error mapping must not return Absinthe error envelopes"
  end

  test "broad Ash authorization bypasses are explicitly ledgered" do
    unapproved =
      ash_authorization_bypasses()
      |> Enum.reject(&auth_bypass_ledger_approves_operation?(auth_bypass_ledger_entries(), &1))

    assert unapproved == [],
           """
           Found authorize?: false call sites without explicit exception ledger approval.
           Each approval must document the file, function, bypass scope, reason, verification, and retirement condition in #{@architecture_exception_ledger}.

           #{format_auth_bypasses(unapproved)}
           """
  end

  test "authorization bypass ledger entries still point to current code" do
    current_tuples =
      ash_authorization_bypasses()
      |> MapSet.new(&{&1.path, &1.function})

    missing =
      for entry <- auth_bypass_ledger_entries(),
          not MapSet.member?(current_tuples, {entry.path, entry.function}) do
        "#{entry.path} #{entry.function}"
      end

    assert missing == [],
           "#{@architecture_exception_ledger} contains authorization bypass entries with no matching current code:\n#{format_errors(missing)}"
  end

  test "authorization bypass ledger records required approval metadata" do
    errors =
      @architecture_exception_ledger
      |> File.read!()
      |> auth_bypass_ledger_metadata_errors()

    assert errors == [],
           """
           #{@architecture_exception_ledger} authorization bypass entries must document owner, approved functions, bypass scope, approving spec, reason, verification coverage, and retirement condition:
           #{format_errors(errors)}
           """
  end

  @tag :scanner_contract
  test "direct Ecto scanner reports proposed-change transaction boundaries" do
    operations =
      direct_ecto_operations()
      |> Enum.filter(&(&1.path == "lib/office_graph/proposed_changes.ex"))
      |> MapSet.new(&{&1.path, &1.function, &1.operation})

    assert operations ==
             MapSet.new([
               {"lib/office_graph/proposed_changes.ex", "apply_all/3", "Repo.transaction"},
               {"lib/office_graph/proposed_changes.ex", "create_for_manual_intake/4",
                "Repo.transaction"}
             ])
  end

  @tag :scanner_contract
  test "traceability contexts no longer use direct Ecto mutations or aggregate reads" do
    forbidden_paths =
      MapSet.new([
        "lib/office_graph/operations.ex",
        "lib/office_graph/audit.ex",
        "lib/office_graph/revisions.ex"
      ])

    operations =
      direct_ecto_operations()
      |> Enum.filter(&(&1.path in forbidden_paths))

    assert operations == [],
           "Traceability contexts must create/count through Ash actions:\n#{format_direct_operations(operations)}"
  end

  @tag :scanner_contract
  test "direct Ecto ledger approval requires exact path function operation tuples" do
    entries =
      parse_direct_ecto_ledger_entries("""
      | File | Function | Operation |
      | --- | --- | --- |
      | `lib/example.ex` | `allowed/0` | `Repo.insert` |
      | `lib/example.ex` | `{other/0, Repo.update}` | Synthetic tuple approval |
      """)

    assert ledger_approves_operation?(entries, %{
             path: "lib/example.ex",
             function: "allowed/0",
             operation: "Repo.insert"
           })

    refute ledger_approves_operation?(entries, %{
             path: "lib/example.ex",
             function: "other/0",
             operation: "Repo.insert"
           })
  end
end
