defmodule OfficeGraph.Repo.Migrations.RestoreRunsScopeIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:runs, [:organization_id, :workspace_id, :inserted_at, :id],
             name: "runs_scope_inserted_at_id_index"
           )
  end

  def down do
    drop_if_exists index(:runs, [:organization_id, :workspace_id, :inserted_at, :id],
                     name: "runs_scope_inserted_at_id_index"
                   )
  end
end
