defmodule OfficeGraph.Repo.Migrations.RestoreDirectoryUserPrincipalIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:enterprise_directory_users, [:principal_id],
             name: "enterprise_directory_users_principal_id_index"
           )
  end

  def down do
    drop_if_exists index(:enterprise_directory_users, [:principal_id],
                     name: "enterprise_directory_users_principal_id_index"
                   )
  end
end
