defmodule OfficeGraph.Repo.Migrations.AddressPr34BotReviewFindings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sessions) do
      add :enterprise_connection_id, :uuid
    end
  end

  def down do
    alter table(:sessions) do
      remove :enterprise_connection_id
    end
  end
end
