defmodule OfficeGraph.Repo.Migrations.RetainWorkosProviderIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:external_identity_links) do
      add :provider_identity_id, :text
    end
  end

  def down do
    alter table(:external_identity_links) do
      remove :provider_identity_id
    end
  end
end
