defmodule OfficeGraph.Repo.Migrations.IntegrateWorkosEnterpriseIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @uuid_v7_primary_key_tables [
    :enterprise_identity_connections,
    :enterprise_directory_memberships,
    :enterprise_directory_users,
    :enterprise_directory_groups,
    :external_group_role_mappings,
    :enterprise_directories,
    :enterprise_directory_sync_events
  ]

  def up do
    create table(:enterprise_identity_connections, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :provider, :text, null: false
      add :provider_organization_id, :text, null: false
      add :directory_requirement, :text, null: false
      add :status, :text, null: false

      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "enterprise_identity_connections_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "enterprise_identity_connections_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :webhook_principal_id,
          references(:principals,
            column: :id,
            name: "enterprise_identity_connections_webhook_principal_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :operation_id,
          references(:operation_correlations,
            column: :id,
            name: "enterprise_identity_connections_operation_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:enterprise_identity_connections, [:provider, :provider_organization_id],
             name: "enterprise_identity_connections_provider_organization_index"
           )

    create table(:enterprise_directory_memberships, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :status, :text, null: false
      add :active_identity_slot, :text
      add :provider_updated_at, :utc_datetime_usec, null: false
      add :removed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :directory_user_id, :uuid, null: false
      add :directory_group_id, :uuid, null: false
    end

    create unique_index(
             :enterprise_directory_memberships,
             [:directory_user_id, :directory_group_id, :active_identity_slot],
             name: "enterprise_directory_memberships_active_membership_index"
           )

    create table(:enterprise_directory_users, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:enterprise_directory_memberships) do
      modify :directory_user_id,
             references(:enterprise_directory_users,
               column: :id,
               name: "enterprise_directory_memberships_directory_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:enterprise_directory_users) do
      add :provider_user_id, :text, null: false
      add :idp_id, :text
      add :email, :text, null: false
      add :first_name, :text
      add :last_name, :text
      add :status, :text, null: false
      add :review_reason, :text
      add :principal_origin, :text
      add :provider_updated_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :directory_id, :uuid, null: false
      add :principal_id, :uuid
      add :external_identity_link_id, :uuid
    end

    create unique_index(:enterprise_directory_users, [:directory_id, :idp_id],
             name: "enterprise_directory_users_idp_user_index"
           )

    create unique_index(:enterprise_directory_users, [:directory_id, :provider_user_id],
             name: "enterprise_directory_users_provider_user_index"
           )

    create table(:enterprise_directory_groups, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:enterprise_directory_memberships) do
      modify :directory_group_id,
             references(:enterprise_directory_groups,
               column: :id,
               name: "enterprise_directory_memberships_directory_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:enterprise_directory_groups) do
      add :provider_group_id, :text, null: false
      add :name, :text, null: false
      add :status, :text, null: false
      add :provider_updated_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :directory_id, :uuid, null: false
    end

    create unique_index(:enterprise_directory_groups, [:directory_id, :provider_group_id],
             name: "enterprise_directory_groups_provider_group_index"
           )

    create table(:external_group_role_mappings, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :status, :text, null: false
      add :active_identity_slot, :text
      add :disabled_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :directory_group_id,
          references(:enterprise_directory_groups,
            column: :id,
            name: "external_group_role_mappings_directory_group_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :role_id,
          references(:roles,
            column: :id,
            name: "external_group_role_mappings_role_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "external_group_role_mappings_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "external_group_role_mappings_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :operation_id,
          references(:operation_correlations,
            column: :id,
            name: "external_group_role_mappings_operation_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(
             :external_group_role_mappings,
             [
               :directory_group_id,
               :role_id,
               :organization_id,
               :workspace_id,
               :active_identity_slot
             ], name: "external_group_role_mappings_active_mapping_index", nulls_distinct: false)

    create table(:enterprise_directories, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:enterprise_directory_users) do
      modify :directory_id,
             references(:enterprise_directories,
               column: :id,
               name: "enterprise_directory_users_directory_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :principal_id,
             references(:principals,
               column: :id,
               name: "enterprise_directory_users_principal_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :external_identity_link_id,
             references(:external_identity_links,
               column: :id,
               name: "enterprise_directory_users_external_identity_link_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:enterprise_directory_groups) do
      modify :directory_id,
             references(:enterprise_directories,
               column: :id,
               name: "enterprise_directory_groups_directory_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:enterprise_directories) do
      add :provider_directory_id, :text, null: false
      add :status, :text, null: false
      add :provider_updated_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :connection_id,
          references(:enterprise_identity_connections,
            column: :id,
            name: "enterprise_directories_connection_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :operation_id,
          references(:operation_correlations,
            column: :id,
            name: "enterprise_directories_operation_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:enterprise_directories, [:provider_directory_id],
             name: "enterprise_directories_provider_directory_index"
           )

    create table(:enterprise_directory_sync_events, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :provider_event_id, :text, null: false
      add :event_type, :text, null: false
      add :content_hash, :text, null: false
      add :status, :text, null: false
      add :result, :text
      add :provider_occurred_at, :utc_datetime_usec, null: false
      add :processed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :connection_id,
          references(:enterprise_identity_connections,
            column: :id,
            name: "enterprise_directory_sync_events_connection_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :directory_id,
          references(:enterprise_directories,
            column: :id,
            name: "enterprise_directory_sync_events_directory_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :raw_archive_id,
          references(:raw_archives,
            column: :id,
            name: "enterprise_directory_sync_events_raw_archive_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :operation_id,
          references(:operation_correlations,
            column: :id,
            name: "enterprise_directory_sync_events_operation_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:enterprise_directory_sync_events, [:provider_event_id],
             name: "enterprise_directory_sync_events_provider_event_index"
           )

    for table_name <- @uuid_v7_primary_key_tables do
      alter table(table_name) do
        modify :id, :uuid, null: false, default: fragment("uuidv7()")
      end
    end
  end

  def down do
    drop constraint(
           :enterprise_directory_sync_events,
           "enterprise_directory_sync_events_connection_id_fkey"
         )

    drop constraint(
           :enterprise_directory_sync_events,
           "enterprise_directory_sync_events_directory_id_fkey"
         )

    drop constraint(
           :enterprise_directory_sync_events,
           "enterprise_directory_sync_events_raw_archive_id_fkey"
         )

    drop constraint(
           :enterprise_directory_sync_events,
           "enterprise_directory_sync_events_operation_id_fkey"
         )

    drop_if_exists unique_index(:enterprise_directory_sync_events, [:provider_event_id],
                     name: "enterprise_directory_sync_events_provider_event_index"
                   )

    drop table(:enterprise_directory_sync_events)

    drop constraint(:enterprise_directories, "enterprise_directories_connection_id_fkey")

    drop_if_exists unique_index(:enterprise_directories, [:provider_directory_id],
                     name: "enterprise_directories_provider_directory_index"
                   )

    alter table(:enterprise_directories) do
      remove :connection_id
      remove :updated_at
      remove :inserted_at
      remove :provider_updated_at
      remove :status
      remove :provider_directory_id
    end

    drop constraint(:enterprise_directory_groups, "enterprise_directory_groups_directory_id_fkey")

    alter table(:enterprise_directory_groups) do
      modify :directory_id, :uuid
    end

    drop constraint(:enterprise_directory_users, "enterprise_directory_users_directory_id_fkey")

    drop constraint(:enterprise_directory_users, "enterprise_directory_users_principal_id_fkey")

    drop constraint(
           :enterprise_directory_users,
           "enterprise_directory_users_external_identity_link_id_fkey"
         )

    alter table(:enterprise_directory_users) do
      modify :external_identity_link_id, :uuid
      modify :principal_id, :uuid
      modify :directory_id, :uuid
    end

    drop table(:enterprise_directories)

    drop constraint(
           :external_group_role_mappings,
           "external_group_role_mappings_directory_group_id_fkey"
         )

    drop constraint(:external_group_role_mappings, "external_group_role_mappings_role_id_fkey")

    drop constraint(
           :external_group_role_mappings,
           "external_group_role_mappings_organization_id_fkey"
         )

    drop constraint(
           :external_group_role_mappings,
           "external_group_role_mappings_workspace_id_fkey"
         )

    drop constraint(
           :external_group_role_mappings,
           "external_group_role_mappings_operation_id_fkey"
         )

    drop_if_exists unique_index(
                     :external_group_role_mappings,
                     [
                       :directory_group_id,
                       :role_id,
                       :organization_id,
                       :workspace_id,
                       :active_identity_slot
                     ], name: "external_group_role_mappings_active_mapping_index")

    drop table(:external_group_role_mappings)

    drop_if_exists unique_index(:enterprise_directory_groups, [:directory_id, :provider_group_id],
                     name: "enterprise_directory_groups_provider_group_index"
                   )

    alter table(:enterprise_directory_groups) do
      remove :directory_id
      remove :updated_at
      remove :inserted_at
      remove :provider_updated_at
      remove :status
      remove :name
      remove :provider_group_id
    end

    drop constraint(
           :enterprise_directory_memberships,
           "enterprise_directory_memberships_directory_group_id_fkey"
         )

    alter table(:enterprise_directory_memberships) do
      modify :directory_group_id, :uuid
    end

    drop table(:enterprise_directory_groups)

    drop_if_exists unique_index(:enterprise_directory_users, [:directory_id, :provider_user_id],
                     name: "enterprise_directory_users_provider_user_index"
                   )

    drop_if_exists unique_index(:enterprise_directory_users, [:directory_id, :idp_id],
                     name: "enterprise_directory_users_idp_user_index"
                   )

    alter table(:enterprise_directory_users) do
      remove :external_identity_link_id
      remove :principal_id
      remove :directory_id
      remove :updated_at
      remove :inserted_at
      remove :provider_updated_at
      remove :review_reason
      remove :status
      remove :last_name
      remove :first_name
      remove :email
      remove :idp_id
      remove :provider_user_id
    end

    drop constraint(
           :enterprise_directory_memberships,
           "enterprise_directory_memberships_directory_user_id_fkey"
         )

    alter table(:enterprise_directory_memberships) do
      modify :directory_user_id, :uuid
    end

    drop table(:enterprise_directory_users)

    drop_if_exists unique_index(
                     :enterprise_directory_memberships,
                     [:directory_user_id, :directory_group_id, :active_identity_slot],
                     name: "enterprise_directory_memberships_active_membership_index"
                   )

    drop table(:enterprise_directory_memberships)

    drop constraint(
           :enterprise_identity_connections,
           "enterprise_identity_connections_organization_id_fkey"
         )

    drop constraint(
           :enterprise_identity_connections,
           "enterprise_identity_connections_workspace_id_fkey"
         )

    drop_if_exists unique_index(
                     :enterprise_identity_connections,
                     [:provider, :provider_organization_id],
                     name: "enterprise_identity_connections_provider_organization_index"
                   )

    drop table(:enterprise_identity_connections)
  end
end
