defmodule OfficeGraph.Repo.Migrations.AddDirectoryEventReceiptOrder do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:enterprise_directory_memberships) do
      add :provider_received_at, :utc_datetime_usec
      add :provider_event_id, :text
    end

    create index(
             :enterprise_directory_memberships,
             [
               :directory_user_id,
               :directory_group_id,
               :provider_updated_at,
               :provider_received_at,
               :provider_event_id,
               :id
             ], name: "enterprise_directory_memberships_order_index")

    alter table(:enterprise_directory_users) do
      add :provider_received_at, :utc_datetime_usec
      add :provider_event_id, :text
    end

    alter table(:enterprise_directory_groups) do
      add :provider_received_at, :utc_datetime_usec
      add :provider_event_id, :text
    end
  end

  def down do
    alter table(:enterprise_directory_groups) do
      remove :provider_event_id
      remove :provider_received_at
    end

    alter table(:enterprise_directory_users) do
      remove :provider_event_id
      remove :provider_received_at
    end

    drop_if_exists index(
                     :enterprise_directory_memberships,
                     [
                       :directory_user_id,
                       :directory_group_id,
                       :provider_updated_at,
                       :provider_received_at,
                       :provider_event_id,
                       :id
                     ], name: "enterprise_directory_memberships_order_index")

    alter table(:enterprise_directory_memberships) do
      remove :provider_event_id
      remove :provider_received_at
    end
  end
end
