defmodule OfficeGraph.Repo.Migrations.RestoreConversationMessageHistoryIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:conversation_messages, [:conversation_id, :inserted_at, :id],
             name: "conversation_messages_conversation_inserted_at_index"
           )
  end

  def down do
    drop_if_exists index(:conversation_messages, [:conversation_id, :inserted_at, :id],
                     name: "conversation_messages_conversation_inserted_at_index"
                   )
  end
end
