defmodule OfficeGraph.Repo.Migrations.RestoreIdentityLookupIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:oidc_login_transactions, [:expires_at],
             name: "oidc_login_transactions_expires_at_index"
           )

    create index(:external_identity_links, [:principal_id],
             name: "external_identity_links_principal_id_index"
           )

    create index(:external_identity_links, [:verified_email],
             name: "external_identity_links_verified_email_index"
           )
  end

  def down do
    drop_if_exists index(:external_identity_links, [:verified_email],
                     name: "external_identity_links_verified_email_index"
                   )

    drop_if_exists index(:external_identity_links, [:principal_id],
                     name: "external_identity_links_principal_id_index"
                   )

    drop_if_exists index(:oidc_login_transactions, [:expires_at],
                     name: "oidc_login_transactions_expires_at_index"
                   )
  end
end
