defmodule OfficeGraph.Repo.Migrations.RestoreReviewedAccessPathIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(
             :graph_relationships,
             [:organization_id, :workspace_id, :lifecycle, :target_item_id, :inserted_at, :id],
             name: "graph_relationships_scope_target_history_index"
           )

    create index(
             :graph_relationships,
             [:organization_id, :workspace_id, :lifecycle, :source_item_id, :inserted_at, :id],
             name: "graph_relationships_scope_source_history_index"
           )

    create index(:github_outbound_actions, [:installation_id, :updated_at, :id],
             name: "github_outbound_actions_installation_updated_at_id_index"
           )

    create index(
             :work_packet_version_sources,
             [:organization_id, :workspace_id, :graph_item_id, :work_packet_version_id],
             name: "work_packet_version_sources_scope_graph_item_version_index"
           )

    create index(:github_sync_outcomes, [:installation_id, :updated_at, :id],
             name: "github_sync_outcomes_installation_updated_at_id_index"
           )
  end

  def down do
    drop_if_exists index(:github_sync_outcomes, [:installation_id, :updated_at, :id],
                     name: "github_sync_outcomes_installation_updated_at_id_index"
                   )

    drop_if_exists index(
                     :work_packet_version_sources,
                     [:organization_id, :workspace_id, :graph_item_id, :work_packet_version_id],
                     name: "work_packet_version_sources_scope_graph_item_version_index"
                   )

    drop_if_exists index(:github_outbound_actions, [:installation_id, :updated_at, :id],
                     name: "github_outbound_actions_installation_updated_at_id_index"
                   )

    drop_if_exists index(
                     :graph_relationships,
                     [
                       :organization_id,
                       :workspace_id,
                       :lifecycle,
                       :source_item_id,
                       :inserted_at,
                       :id
                     ], name: "graph_relationships_scope_source_history_index")

    drop_if_exists index(
                     :graph_relationships,
                     [
                       :organization_id,
                       :workspace_id,
                       :lifecycle,
                       :target_item_id,
                       :inserted_at,
                       :id
                     ], name: "graph_relationships_scope_target_history_index")
  end
end
