defmodule OfficeGraph.Repo.Migrations.RestoreAgentExecutionHistoryIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:agent_executions, [:run_id, :graph_item_id, :inserted_at, :id],
             name: "agent_executions_run_graph_item_inserted_at_id_index"
           )
  end

  def down do
    drop_if_exists index(:agent_executions, [:run_id, :graph_item_id, :inserted_at, :id],
                     name: "agent_executions_run_graph_item_inserted_at_id_index"
                   )
  end
end
