defmodule OfficeGraph.Repo.Migrations.RestoreRunAndScopeAccessPathIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:evidence_items, [:work_run_id, :inserted_at, :id],
             name: "evidence_items_work_run_inserted_at_id_index"
           )

    create index(:verification_results, [:work_run_id, :inserted_at, :id],
             name: "verification_results_work_run_inserted_at_id_index"
           )

    create index(:graph_items, [:organization_id, :workspace_id, :id],
             name: "graph_items_scope_id_index"
           )

    create index(:execution_observations, [:work_run_id, :inserted_at, :id],
             name: "execution_observations_work_run_inserted_at_id_index"
           )

    create index(:domain_events, [:operation_id], name: "domain_events_operation_id_index")

    create index(:evidence_candidates, [:work_run_id, :inserted_at, :id],
             name: "evidence_candidates_work_run_inserted_at_id_index"
           )
  end

  def down do
    drop_if_exists index(:evidence_candidates, [:work_run_id, :inserted_at, :id],
                     name: "evidence_candidates_work_run_inserted_at_id_index"
                   )

    drop_if_exists index(:domain_events, [:operation_id],
                     name: "domain_events_operation_id_index"
                   )

    drop_if_exists index(:execution_observations, [:work_run_id, :inserted_at, :id],
                     name: "execution_observations_work_run_inserted_at_id_index"
                   )

    drop_if_exists index(:graph_items, [:organization_id, :workspace_id, :id],
                     name: "graph_items_scope_id_index"
                   )

    drop_if_exists index(:verification_results, [:work_run_id, :inserted_at, :id],
                     name: "verification_results_work_run_inserted_at_id_index"
                   )

    drop_if_exists index(:evidence_items, [:work_run_id, :inserted_at, :id],
                     name: "evidence_items_work_run_inserted_at_id_index"
                   )
  end
end
