defmodule OfficeGraph.WorkGraph.ReferenceCatalog do
  @moduledoc false

  @definitions [
    {"contained_in", "containment", "The source item belongs to the target scope item.",
     "forbid"},
    {"decomposes_to", "decomposition",
     "The source item is decomposed into the target work, finding, or check item.", "forbid"},
    {"depends_on", "dependency", "The source work item depends on the target work item.",
     "forbid"},
    {"blocked_by", "blocking", "The source work item is blocked by the target work item.",
     "forbid"},
    {"generated_from", "provenance", "The source item was generated from the target source item.",
     "allow"},
    {"requires_check", "verification", "The source item requires the target verification check.",
     "allow"},
    {"satisfied_by", "requirement_satisfaction",
     "The source item is satisfied by the target result or evidence.", "allow"},
    {"evidenced_by", "evidence", "The source item is evidenced by the target evidence or result.",
     "allow"},
    {"review_finding_for", "review",
     "The source review finding applies to the target reviewed item.", "allow"},
    {"discussed_in", "discussion", "The source item is discussed in the target conversation.",
     "allow"},
    {"references_external", "external_reference",
     "The source item references the target external-reference item.", "allow"},
    {"affects_scope", "affected_scope",
     "The source item affects the target scope or scoped resource.", "allow"}
  ]

  @rules [
    {"contained_in", "signal", "initiative"},
    {"contained_in", "task", "initiative"},
    {"contained_in", "review_finding", "initiative"},
    {"contained_in", "verification_check", "initiative"},
    {"contained_in", "artifact", "initiative"},
    {"contained_in", "evidence_item", "initiative"},
    {"contained_in", "task", "workstream"},
    {"decomposes_to", "signal", "task"},
    {"decomposes_to", "task", "task"},
    {"decomposes_to", "task", "review_finding"},
    {"decomposes_to", "task", "verification_check"},
    {"decomposes_to", "requirement", "task"},
    {"decomposes_to", "decision", "task"},
    {"depends_on", "task", "task"},
    {"depends_on", "requirement", "requirement"},
    {"depends_on", "work_packet", "work_packet"},
    {"depends_on", "run", "run"},
    {"blocked_by", "task", "task"},
    {"blocked_by", "requirement", "requirement"},
    {"blocked_by", "work_packet", "work_packet"},
    {"blocked_by", "run", "run"},
    {"generated_from", "task", "signal"},
    {"generated_from", "review_finding", "task"},
    {"generated_from", "verification_check", "review_finding"},
    {"generated_from", "evidence_item", "artifact"},
    {"generated_from", "artifact", "evidence_item"},
    {"generated_from", "work_packet", "signal"},
    {"generated_from", "run", "work_packet"},
    {"generated_from", "proposal", "signal"},
    {"requires_check", "task", "verification_check"},
    {"requires_check", "review_finding", "verification_check"},
    {"requires_check", "requirement", "verification_check"},
    {"requires_check", "decision", "verification_check"},
    {"satisfied_by", "task", "verification_result"},
    {"satisfied_by", "requirement", "verification_result"},
    {"satisfied_by", "verification_check", "verification_result"},
    {"satisfied_by", "review_finding", "verification_result"},
    {"satisfied_by", "task", "evidence_item"},
    {"satisfied_by", "requirement", "evidence_item"},
    {"evidenced_by", "task", "evidence_item"},
    {"evidenced_by", "review_finding", "evidence_item"},
    {"evidenced_by", "verification_check", "evidence_item"},
    {"evidenced_by", "run", "evidence_item"},
    {"evidenced_by", "verification_check", "verification_result"},
    {"review_finding_for", "review_finding", "task"},
    {"discussed_in", "signal", "conversation"},
    {"discussed_in", "task", "conversation"},
    {"discussed_in", "review_finding", "conversation"},
    {"discussed_in", "verification_check", "conversation"},
    {"discussed_in", "artifact", "conversation"},
    {"discussed_in", "evidence_item", "conversation"},
    {"references_external", "signal", "external_reference"},
    {"references_external", "task", "external_reference"},
    {"references_external", "review_finding", "external_reference"},
    {"references_external", "verification_check", "external_reference"},
    {"references_external", "artifact", "external_reference"},
    {"references_external", "evidence_item", "external_reference"},
    {"affects_scope", "signal", "initiative"},
    {"affects_scope", "task", "initiative"},
    {"affects_scope", "review_finding", "initiative"},
    {"affects_scope", "verification_check", "initiative"},
    {"affects_scope", "proposal", "initiative"},
    {"affects_scope", "signal", "workstream"},
    {"affects_scope", "task", "workstream"},
    {"affects_scope", "proposal", "workspace"}
  ]

  def definitions do
    Enum.map(@definitions, fn {key, family, meaning, cycle_policy} ->
      %{
        key: key,
        family: family,
        direction: "directed",
        meaning: meaning,
        lifecycle: "active",
        provenance_policy: "operation_required",
        authorization_policy: "authorize_scope_and_endpoints",
        cycle_policy: cycle_policy,
        specialization_posture: "registered"
      }
    end)
  end

  def rules, do: @rules
end
